language: php

php:
  - 7.0

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - nvm install 5.5.0
  - nvm use 5.5.0

install:
  - cp .env.travis .env
  - mysql -e 'create database simplewiki;'
  - source .env
  - npm install
  - composer install
#  - bower install

before_script:
  - php artisan db:seed
#  - 'export DISPLAY=:99.0'
#  - 'sh -e /etc/init.d/xvfb start'
#  - 'node_modules/protractor/bin/webdriver-manager update'
#  - nohup bash -c  'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
#  - 'php artisan serve 2>&1 &'
#  - sleep 3 # give xvfb some time to start

script:
#  - ./phpunit.sh
#  - ./protractor.sh

branches:
  only:
    - master
    - stable
